// <auto-generated />
using System;
using Mango.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "This is Punjabi Samosa",
                            ImageUrl = "https://sukhis.com/wp-content/uploads/2019/07/Samosa-1.png",
                            Name = "Samosa",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Entree",
                            Description = "This is Paneer Tikka Masala",
                            ImageUrl = "https://www.cookwithmanali.com/wp-content/uploads/2014/03/Paneer-Tikka-Masala-500x375.jpg",
                            Name = "Paneer Tikka Masala",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Dessert",
                            Description = "This is Sweet Pie",
                            ImageUrl = "https://www.196flavors.com/wp-content/uploads/2014/10/pithiviers-3-FP.jpg",
                            Name = "Sweet Pie",
                            Price = 10.99
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Appetizer",
                            Description = "This is Pav Bhaji",
                            ImageUrl = "https://www.cookwithmanali.com/wp-content/uploads/2014/03/Paneer-Tikka-Masala-500x375.jpg",
                            Name = "Pav Bhaji",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Entree",
                            Description = "This is Dosa",
                            ImageUrl = "https://www.cookwithmanali.com/wp-content/uploads/2014/03/Paneer-Tikka-Masala-500x375.jpg",
                            Name = "Dosa",
                            Price = 22.989999999999998
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Dessert",
                            Description = "This is Gulab Jamun",
                            ImageUrl = "https://www.cookwithmanali.com/wp-content/uploads/2014/03/Paneer-Tikka-Masala-500x375.jpg",
                            Name = "Gulab Jamun",
                            Price = 10.99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
